name: junitreport
version: 2.0.3-dev
description: Generate JUnit XML reports from dart test runs. Transforms the output of dart or flutter tests to
  JUnit style XML

homepage: https://github.com/TOPdesk/dart-junitreport
documentation:

dependencies:
  args: ^2.3.2
  intl: ^0.17.0
  testreport: ^2.0.1
  xml: ^6.2.2

dev_dependencies:
  test: any
  lints: 1.0.1

environment:
  sdk: '>=2.14.0 <3.0.0'

executables:
  tojunit: