name: junitreport
version: 2.0.4-dev
description: Generate JUnit XML reports from dart test runs. Transforms the output of dart or flutter tests to
  JUnit style XML

homepage: https://github.com/TOPdesk/dart-junitreport
documentation: See Upstram

dependencies:
  args: ^2.4.2
  intl: ^0.19.0
  testreport: ^2.0.1
  xml: ^6.5.0

dev_dependencies:
  test: any
  lints: 3.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'

executables:
  tojunit:
